name: lvd-pg
channels:
  - conda-forge
dependencies:
  - _openmp_mutex
  - annotated-doc
  - anyio
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - azure-storage-files-datalake-cpp
  - blas
  - blas-devel
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - click
  - contourpy
  - cpython=3.11
  - cycler
  - einops
  - faiss-gpu
  - filelock
  - fmt
  - fonttools
  - freetype
  - gflags
  - giflib
  - glog
  - gmp
  - gmpy2
  - h11
  - hf-xet
  - httpcore
  - httpx
  - huggingface_hub
  - idna
  - jinja2
  - joblib
  - julia
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libarrow
  - libarrow-acero
  - libarrow-compute
  - libarrow-dataset
  - libarrow-substrait
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libfaiss-gpu
  - libffi
  - libfreetype
  - libfreetype6
  - libgcc
  - libgfortran
  - libgfortran5
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - liblapack
  - liblapacke
  - liblzma
  - libmpdec
  - libnghttp2
  - libopenblas
  - libopentelemetry-cpp
  - libopentelemetry-cpp-headers
  - libparquet
  - libpng
  - libprotobuf
  - libre2-11
  - libsqlite
  - libssh2
  - libthrift
  - libtiff
  - libtorch
  - libutf8proc
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libxml2-16
  - libzlib
  - llvm-openmp
  - lz4-c
  - markdown-it-py
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mdurl
  - mpc
  - mpfr
  - mpmath
  - munkres
  - narwhals
  - ncurses
  - networkx
  - nlohmann_json
  - nomkl
  - numpy
  - openblas
  - openjpeg
  - openssl
  - optree
  - orc
  - packaging
  - pillow
  - pip
  - prometheus-cpp
  - pthread-stubs
  - pytorch-cuda
  - pyarrow
  - pyarrow-core
  - pybind11
  - pybind11-abi
  - pybind11-global
  - pygments
  - pyparsing
  - python=3.11
  - python-dateutil
  - python_abi=3.11
  - pytorch
  - pyyaml
  - qhull
  - re2
  - readline
  - regex
  - rich
  - safetensors
  - scikit-learn
  - scipy
  - setuptools
  - shellingham
  - six
  - sleef
  - snappy
  - sympy
  - threadpoolctl
  - tk
  - tokenizers
  - torchvision
  - tornado
  - tqdm
  - transformers
  - typer
  - typer-slim
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - xorg-libxau
  - xorg-libxdmcp
  - yaml
  - zlib
  - zlib-ng
  - zstd
  - pip:
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - attrs
      - beartype
      - charset-normalizer
      - datasets
      - dill
      - frozenlist
      - fsspec
      - jaxtyping
      - multidict
      - multiprocess
      - pandas
      - propcache
      - requests
      - urllib3
      - wadler-lindig
      - xxhash
      - yarl
